import "./globals.css";

import type { Metadata } from "next";
import React from "react";

import { Toaster } from "@/components/ui/Toaster";

export const metadata: Metadata = {
  title: "АВС Просмотр: Главная",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        {children}
        <Toaster />
      </body>
    </html>
  );
}
